name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23', '1.22', '1.21' ]
        tags: [ 'strftime_native_errors', '' ]
      fail-fast: false
    name: "Go ${{ matrix.go }} test (tags: ${{ matrix.tags }})"
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Go stable version
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go }}
      - name: Test with coverage
        run: make STRFTIME_TAGS=${{ matrix.tags }} cover
      - name: Upload code coverage to codecov
        if: matrix.go == '1.23'
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00  # v5.5.0
        with:
          file: ./coverage.out
