name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23', '1.22', '1.21' ]
        tags: [ 'strftime_native_errors', '' ]
      fail-fast: false
    name: "Go ${{ matrix.go }} test (tags: ${{ matrix.tags }})"
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install Go stable version
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ matrix.go }}
      - name: Test with coverage
        run: make STRFTIME_TAGS=${{ matrix.tags }} cover
      - name: Upload code coverage to codecov
        if: matrix.go == '1.23'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
        with:
          file: ./coverage.out
